from django.core.management.base import BaseCommand
from quiz.models import QuestionCategory, Question

class Command(BaseCommand):
    help = 'Seed the database with 200 quiz questions'

    def handle(self, *args, **options):
        # Get or create categories
        categories_config = {
            'spiritual': 'Spiritual Knowing',
            'mental': 'Mental Knowing',
            'physical': 'Physical Knowing',
            'disagreeables': 'Disagreeables & Truth Checks',
            'romantic': 'Romantic Knowing',
            'erotic': 'Erotic Knowing',
            'creative': 'Creative & Fun',
        }
        
        categories = {}
        for cat_code, cat_name in categories_config.items():
            cat_obj, _ = QuestionCategory.objects.get_or_create(
                category=cat_code,
                defaults={'name': cat_name, 'description': f'{cat_name} questions'}
            )
            categories[cat_code] = cat_obj

        questions_data = {
            'spiritual': [
                ('What is one thing that makes you feel most at peace?', 'Describe your happiest moment together', 1),
                ('How do you define spirituality in your own words?', 'Share what spirituality means to you', 2),
                ('What role does faith play in your life?', 'Tell me about your spiritual journey', 2),
                ('Describe a moment when you felt connected to something larger than yourself', 'Share a spiritual awakening', 3),
                ('What does it mean to be fully present with another person?', 'Explain complete presence', 1),
                ('How do you find meaning in everyday moments?', 'Share your purpose discovery', 2),
                ('What would a perfect day of spiritual connection look like for us?', 'Design our spiritual day', 3),
                ('How do you handle moments of doubt or disconnection?', 'Discuss your doubts', 2),
                ('What practices help you feel more grounded and centered?', 'Share your grounding rituals', 1),
                ('Describe the most profound conversation you\'ve ever had', 'Share your deepest talk', 3),
                ('What spiritual value is most important to you?', 'Name your core spiritual value', 1),
                ('How can we deepen our spiritual connection together?', 'Suggest ways to connect', 2),
                ('What does unconditional love mean to you?', 'Define your love', 2),
                ('Describe a time when you felt truly heard and understood', 'Share that moment', 2),
                ('What would it mean to live authentically with me?', 'Explore authentic living', 3),
                ('How do you want to be remembered by the people you love?', 'Share your legacy', 3),
                ('What role does gratitude play in your spiritual life?', 'Discuss gratitude', 1),
                ('Describe your ideal moment of intimacy and connection', 'Paint that picture', 2),
                ('What spiritual practice would you like to try together?', 'Suggest a practice', 1),
                ('How do you balance independence with deep connection?', 'Explore this balance', 2),
                ('What are you most grateful for in our relationship?', 'Express gratitude', 1),
                ('Describe a moment when you felt completely safe and loved', 'Share that safety', 2),
                ('What does vulnerability mean to you?', 'Define vulnerability', 2),
                ('How would you want our relationship to evolve spiritually?', 'Share your vision', 3),
                ('What is your biggest fear about true intimacy?', 'Be honest about fears', 2),
                ('Describe the most loving gesture someone has shown you', 'Share that love', 2),
                ('What would make you feel more cherished?', 'Tell me your needs', 1),
                ('How do you express love in its purest form?', 'Describe your love language', 2),
                ('What spiritual belief do you hold most dear?', 'Share your core belief', 1),
                ('Describe a time when you felt your partner truly understand your soul', 'Share that understanding', 3),
            ],
            'mental': [
                ('What is your most common worry?', 'Face your worry', 1),
                ('Describe your biggest dream or aspiration', 'Share your dream', 2),
                ('What would make you feel more confident?', 'Name confidence boosters', 1),
                ('How do you typically handle stress or anxiety?', 'Describe your coping', 1),
                ('What is something you\'ve always wanted to learn?', 'Share a learning goal', 1),
                ('Describe the moment you knew you were truly in love', 'Tell our love story', 3),
                ('What is your biggest insecurity in relationships?', 'Be vulnerable', 2),
                ('How do you want to be supported emotionally?', 'Express your needs', 1),
                ('What thoughts keep you up at night?', 'Share your night thoughts', 2),
                ('Describe a difficult decision you had to make', 'Share your struggle', 2),
                ('What would your ideal future look like?', 'Paint your future', 2),
                ('How do you feel about your body?', 'Explore body image', 2),
                ('What is something you\'ve been afraid to tell me?', 'Confess fearfully', 2),
                ('Describe your relationship with your parents', 'Share family impact', 2),
                ('What does success mean to you?', 'Define success', 1),
                ('How do you want to grow together?', 'Plan growth', 2),
                ('What is your biggest regret?', 'Share a regret', 2),
                ('Describe a moment when you felt truly proud of yourself', 'Share pride', 1),
                ('What would help you feel more secure in our relationship?', 'Name security needs', 1),
                ('How do you handle criticism or feedback?', 'Explore feedback', 1),
                ('What is something you\'re jealous about?', 'Admit jealousy', 1),
                ('Describe your ideal partner before you met me', 'Share old dreams', 1),
                ('What unhealthy thought pattern do you struggle with?', 'Name your pattern', 2),
                ('How do you want to be challenged to grow?', 'Plan challenges', 1),
                ('What is your relationship with money?', 'Explore finances', 2),
                ('Describe a time you felt truly betrayed', 'Share betrayal', 2),
                ('What would make you feel more valued?', 'Name value needs', 1),
                ('How do you typically process emotions?', 'Describe processing', 1),
                ('What is a boundary you need to set?', 'Name boundaries', 1),
                ('Describe your ideal work-life balance', 'Paint balance', 1),
            ],
            'physical': [
                ('What is your love language?', 'Name your language', 1),
                ('How do you like to be touched?', 'Describe touch preferences', 1),
                ('What physical quality do you find most attractive about me?', 'Compliment me physically', 1),
                ('Describe a moment of physical connection that meant everything', 'Share touch memories', 2),
                ('What type of massage would feel amazing right now?', 'Describe dream massage', 1),
                ('How do you want to be kissed?', 'Describe ideal kiss', 1),
                ('What physical activity makes you feel most alive?', 'Share your movement', 1),
                ('Describe your ideal cuddle session', 'Paint intimacy', 1),
                ('What sensations do you crave?', 'Name sensations', 1),
                ('How do you want me to initiate physical contact?', 'Guide my touch', 1),
                ('What is your favorite way to hold hands?', 'Describe hand holding', 1),
                ('Describe how you felt the first time we touched', 'Recall first touch', 2),
                ('What physical experience have you been dreaming about?', 'Share fantasy', 1),
                ('How do you like to move together?', 'Describe movement', 1),
                ('What makes you feel most physically desired?', 'Name desire triggers', 1),
                ('Describe your ideal moment of physical intimacy', 'Paint intimacy', 2),
                ('What do you love about my body?', 'Give physical praise', 1),
                ('How do you want to dance together?', 'Describe dance', 1),
                ('What physical sensation makes you feel most loved?', 'Name love sensations', 1),
                ('Describe a time you felt most physically confident', 'Share confidence', 1),
                ('What would you like to explore physically?', 'Share interests', 2),
                ('How do you want to wake up together?', 'Describe mornings', 1),
                ('What is your favorite physical memory with me?', 'Recall a moment', 1),
                ('Describe the perfect afternoon together', 'Paint perfect day', 1),
                ('How do you want to be held when vulnerable?', 'Guide comfort touch', 1),
                ('What physical play appeals to you?', 'Share play interests', 1),
                ('Describe your ideal shower or bath together', 'Paint water intimacy', 1),
                ('What makes you feel most physically alive?', 'Name vitality', 1),
                ('How do you want physical affection to increase?', 'Guide affection growth', 1),
                ('Describe the moment you felt most physically connected to me', 'Share peak connection', 2),
            ],
            'disagreeables': [
                ('What is the biggest argument we\'ve had?', 'Discuss conflict', 2),
                ('How do you typically react when angry?', 'Describe anger', 1),
                ('What habit of mine bothers you?', 'Be honest', 1),
                ('Describe a time I hurt you deeply', 'Share hurt', 2),
                ('What is something I do that frustrates you?', 'Name frustration', 1),
                ('How do you want me to handle your anger?', 'Guide anger support', 1),
                ('What topic are we most likely to argue about?', 'Name conflict topic', 1),
                ('How could I better support you during conflict?', 'Guide conflict support', 1),
                ('What unresolved issue still bothers you?', 'Face unresolved pain', 2),
                ('How do you think I could improve?', 'Give feedback', 1),
                ('What do you feel I don\'t understand about you?', 'Bridge gap', 1),
                ('Describe a time you felt abandoned by me', 'Share abandonment fear', 2),
                ('What is a deal-breaker for you in relationships?', 'Name deal-breakers', 1),
                ('How do you handle being wrong?', 'Explore accountability', 1),
                ('What fear comes up during arguments?', 'Name conflict fears', 1),
                ('Describe the worst moment in our relationship', 'Share difficult time', 2),
                ('How do you want to rebuild after a fight?', 'Guide reconciliation', 1),
                ('What do you feel I take for granted?', 'Name overlooked things', 1),
                ('How could we better communicate disagreements?', 'Improve communication', 1),
                ('What is something you\'ve never fully forgiven?', 'Face forgiveness', 2),
                ('How do you sabotage relationships?', 'Explore patterns', 1),
                ('What trigger makes you most defensive?', 'Name defensiveness', 1),
                ('Describe the coldest you\'ve felt toward me', 'Share distance', 2),
                ('How do you want to be approached when upset?', 'Guide approach', 1),
                ('What family pattern do you repeat?', 'Explore family patterns', 1),
                ('How do you handle my vulnerability?', 'Explore vulnerability handling', 1),
                ('What compromise is hard for you to make?', 'Name hard compromises', 1),
                ('Describe a time you felt misunderstood', 'Share misunderstanding', 1),
                ('What would make you consider leaving?', 'Be honest about limits', 2),
                ('How can we prevent future conflicts?', 'Build conflict prevention', 1),
            ],
            'romantic': [
                ('When did you first know you loved me?', 'Recall falling in love', 2),
                ('What is the most romantic thing someone has done for you?', 'Share romance', 2),
                ('Describe the perfect date for us', 'Plan ideal date', 1),
                ('How do you want me to romance you?', 'Guide romance', 1),
                ('What would make our relationship feel more special?', 'Enhance specialness', 1),
                ('Describe a moment you felt completely cherished', 'Share cherishment', 2),
                ('What is your greatest hope for us?', 'Share hope', 2),
                ('How do you want to celebrate our milestones?', 'Plan celebrations', 1),
                ('What romantic gesture means most to you?', 'Name meaningful gesture', 1),
                ('Describe our love story as you see it', 'Tell our story', 2),
                ('What would make you feel more courted?', 'Guide courting', 1),
                ('How do you want to express love in public?', 'Describe public affection', 1),
                ('What is the most loving thing I\'ve ever done?', 'Praise me', 2),
                ('Describe your ideal romantic getaway', 'Plan escape', 2),
                ('What do you love about our relationship?', 'Express appreciation', 1),
                ('How do you want our love to grow?', 'Plan growth', 1),
                ('What romantic dream should we pursue together?', 'Share dream', 2),
                ('Describe a moment you felt truly romanced by me', 'Share that moment', 2),
                ('What would make our intimate moments feel more romantic?', 'Enhance romance', 1),
                ('How do you want to be loved?', 'Express love needs', 1),
                ('What small gestures mean the most to you?', 'Name meaningful gestures', 1),
                ('Describe the person you want to become for us', 'Share your vision', 1),
                ('What is your favorite memory of us?', 'Recall favorite moment', 1),
                ('How do you want to stay connected to my heart?', 'Explore connection', 1),
                ('What would be the ultimate romantic gesture?', 'Describe dream gesture', 2),
                ('Describe how you want to grow old together', 'Paint our future', 2),
                ('What do you admire most about me?', 'Give deep compliment', 1),
                ('How can we keep romance alive?', 'Plan romance sustainability', 1),
                ('What is something you\'ve never told me that you love about me?', 'Share hidden love', 2),
                ('Describe the legacy of love you want to build', 'Share love legacy', 2),
            ],
            'erotic': [
                ('What is your biggest turn-on?', 'Share attraction', 1),
                ('Describe your fantasies about me', 'Share fantasies', 2),
                ('What would make you feel most sexually desired?', 'Name desire needs', 1),
                ('How do you like to initiate intimacy?', 'Describe initiation', 1),
                ('What is something you\'ve been curious to try?', 'Name curiosity', 1),
                ('Describe your favorite intimate memory', 'Recall peak intimacy', 2),
                ('What turns you on about my appearance?', 'Give erotic praise', 1),
                ('How do you like to be seduced?', 'Guide seduction', 1),
                ('What is your sexual love language?', 'Define it', 1),
                ('Describe the most satisfying sexual experience', 'Share satisfaction', 2),
                ('What would increase your desire for me?', 'Name desire enhancers', 1),
                ('How do you want to explore sexuality together?', 'Discuss exploration', 1),
                ('What do you love about our sexual connection?', 'Praise our sex', 1),
                ('Describe what makes you feel most sexually confident', 'Share confidence', 1),
                ('What sensation makes you lose control?', 'Name sensation', 1),
                ('How would you like our intimate life to evolve?', 'Plan evolution', 1),
                ('What fantasies have you kept private?', 'Share private fantasy', 2),
                ('Describe your ideal sexual rhythm with me', 'Paint rhythm', 1),
                ('What is off-limits for you sexually?', 'Name boundaries', 1),
                ('How do you want to express raw desire for me?', 'Guide expression', 1),
                ('What position or scenario excites you most?', 'Name excitement', 1),
                ('Describe the most passionate moment we\'ve shared', 'Recall passion', 2),
                ('What do you crave during intimate moments?', 'Name cravings', 1),
                ('How do you want me to touch you?', 'Guide touch', 1),
                ('What would be the ultimate sexual experience with me?', 'Describe ultimate', 2),
                ('How do you want foreplay to unfold?', 'Describe foreplay', 1),
                ('What turns you on about our differences?', 'Explore attraction', 1),
                ('Describe a moment of pure sexual connection', 'Share connection', 2),
                ('What would make you feel more sexually free?', 'Name freedom needs', 1),
                ('How can we create more sexual chemistry?', 'Build chemistry', 1),
            ],
            'creative': [
                ('What is your hidden talent?', 'Share talent', 1),
                ('Describe something you\'d like to create together', 'Plan creation', 1),
                ('What would be a fun challenge for us?', 'Suggest challenge', 1),
                ('Describe your ideal adventure', 'Paint adventure', 2),
                ('What hobby would you like to share with me?', 'Share hobby', 1),
                ('If you could do anything for a day, what would it be?', 'Describe dream day', 1),
                ('What creative project excites you?', 'Name excitement', 1),
                ('Describe a time you felt most inspired', 'Share inspiration', 1),
                ('What would you like to learn from me?', 'Name learning goal', 1),
                ('Describe the perfect creative collaboration', 'Paint collaboration', 1),
                ('What artistic form calls to you?', 'Name art form', 1),
                ('How do you like to have fun?', 'Describe fun', 1),
                ('What experience do you want to share?', 'Name experience', 1),
                ('Describe a place you\'d love to explore together', 'Plan exploration', 1),
                ('What makes you feel most alive and creative?', 'Name aliveness', 1),
                ('Describe your ideal weekend escape', 'Paint escape', 1),
                ('What talent of mine inspires you most?', 'Praise my talent', 1),
                ('How would you like to celebrate together?', 'Plan celebration', 1),
                ('What skill would you like to master together?', 'Name skill', 1),
                ('Describe a game we could play together', 'Invent game', 1),
                ('What spontaneous adventure appeals to you?', 'Name adventure', 1),
                ('How do you want to be playful together?', 'Describe playfulness', 1),
                ('What creative goal excites you for us?', 'Share creative goal', 1),
                ('Describe your ideal rainy day together', 'Paint day', 1),
                ('What would make ordinary moments feel special?', 'Enhance ordinary', 1),
                ('How do you want to express your personality with me?', 'Express fully', 1),
                ('Describe a tradition we should start', 'Create tradition', 1),
                ('What hidden dream should we pursue?', 'Share dream', 1),
                ('How can we inject more joy and laughter?', 'Plan joy', 1),
                ('Describe the most fun you\'ve ever had', 'Share peak fun', 1),
            ],
        }

        created_count = 0
        for category_code, questions_list in questions_data.items():
            category = categories[category_code]
            
            for idx, (question_text, consequence, points) in enumerate(questions_list, 1):
                question, created = Question.objects.get_or_create(
                    category=category,
                    question_text=question_text,
                    defaults={
                        'consequence': consequence,
                        'points': points,
                        'order': idx,
                    }
                )
                if created:
                    created_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f'Successfully created {created_count} questions across {len(questions_data)} categories'
            )
        )

        questions_data = {
            'spiritual': [
                ('What is one thing that makes you feel most at peace?', 'Describe your happiest moment together', 1),
                ('How do you define spirituality in your own words?', 'Share what spirituality means to you', 2),
                ('What role does faith play in your life?', 'Tell me about your spiritual journey', 2),
                ('Describe a moment when you felt connected to something larger than yourself', 'Share a spiritual awakening', 3),
                ('What does it mean to be fully present with another person?', 'Explain complete presence', 1),
                ('How do you find meaning in everyday moments?', 'Share your purpose discovery', 2),
                ('What would a perfect day of spiritual connection look like for us?', 'Design our spiritual day', 3),
                ('How do you handle moments of doubt or disconnection?', 'Discuss your doubts', 2),
                ('What practices help you feel more grounded and centered?', 'Share your grounding rituals', 1),
                ('Describe the most profound conversation you\'ve ever had', 'Share your deepest talk', 3),
                ('What spiritual value is most important to you?', 'Name your core spiritual value', 1),
                ('How can we deepen our spiritual connection together?', 'Suggest ways to connect', 2),
                ('What does unconditional love mean to you?', 'Define your love', 2),
                ('Describe a time when you felt truly heard and understood', 'Share that moment', 2),
                ('What would it mean to live authentically with me?', 'Explore authentic living', 3),
                ('How do you want to be remembered by the people you love?', 'Share your legacy', 3),
                ('What role does gratitude play in your spiritual life?', 'Discuss gratitude', 1),
                ('Describe your ideal moment of intimacy and connection', 'Paint that picture', 2),
                ('What spiritual practice would you like to try together?', 'Suggest a practice', 1),
                ('How do you balance independence with deep connection?', 'Explore this balance', 2),
                ('What are you most grateful for in our relationship?', 'Express gratitude', 1),
                ('Describe a moment when you felt completely safe and loved', 'Share that safety', 2),
                ('What does vulnerability mean to you?', 'Define vulnerability', 2),
                ('How would you want our relationship to evolve spiritually?', 'Share your vision', 3),
                ('What is your biggest fear about true intimacy?', 'Be honest about fears', 2),
                ('Describe the most loving gesture someone has shown you', 'Share that love', 2),
                ('What would make you feel more cherished?', 'Tell me your needs', 1),
                ('How do you express love in its purest form?', 'Describe your love language', 2),
                ('What spiritual belief do you hold most dear?', 'Share your core belief', 1),
                ('Describe a time when you felt your partner truly understand your soul', 'Share that understanding', 3),
            ],
            'mental': [
                ('What is your most common worry?', 'Face your worry', 1),
                ('Describe your biggest dream or aspiration', 'Share your dream', 2),
                ('What would make you feel more confident?', 'Name confidence boosters', 1),
                ('How do you typically handle stress or anxiety?', 'Describe your coping', 1),
                ('What is something you\'ve always wanted to learn?', 'Share a learning goal', 1),
                ('Describe the moment you knew you were truly in love', 'Tell our love story', 3),
                ('What is your biggest insecurity in relationships?', 'Be vulnerable', 2),
                ('How do you want to be supported emotionally?', 'Express your needs', 1),
                ('What thoughts keep you up at night?', 'Share your night thoughts', 2),
                ('Describe a difficult decision you had to make', 'Share your struggle', 2),
                ('What would your ideal future look like?', 'Paint your future', 2),
                ('How do you feel about your body?', 'Explore body image', 2),
                ('What is something you\'ve been afraid to tell me?', 'Confess fearfully', 2),
                ('Describe your relationship with your parents', 'Share family impact', 2),
                ('What does success mean to you?', 'Define success', 1),
                ('How do you want to grow together?', 'Plan growth', 2),
                ('What is your biggest regret?', 'Share a regret', 2),
                ('Describe a moment when you felt truly proud of yourself', 'Share pride', 1),
                ('What would help you feel more secure in our relationship?', 'Name security needs', 1),
                ('How do you handle criticism or feedback?', 'Explore feedback', 1),
                ('What is something you\'re jealous about?', 'Admit jealousy', 1),
                ('Describe your ideal partner before you met me', 'Share old dreams', 1),
                ('What unhealthy thought pattern do you struggle with?', 'Name your pattern', 2),
                ('How do you want to be challenged to grow?', 'Plan challenges', 1),
                ('What is your relationship with money?', 'Explore finances', 2),
                ('Describe a time you felt truly betrayed', 'Share betrayal', 2),
                ('What would make you feel more valued?', 'Name value needs', 1),
                ('How do you typically process emotions?', 'Describe processing', 1),
                ('What is a boundary you need to set?', 'Name boundaries', 1),
                ('Describe your ideal work-life balance', 'Paint balance', 1),
            ],
            'physical': [
                ('What is your love language?', 'Name your language', 1),
                ('How do you like to be touched?', 'Describe touch preferences', 1),
                ('What physical quality do you find most attractive about me?', 'Compliment me physically', 1),
                ('Describe a moment of physical connection that meant everything', 'Share touch memories', 2),
                ('What type of massage would feel amazing right now?', 'Describe dream massage', 1),
                ('How do you want to be kissed?', 'Describe ideal kiss', 1),
                ('What physical activity makes you feel most alive?', 'Share your movement', 1),
                ('Describe your ideal cuddle session', 'Paint intimacy', 1),
                ('What sensations do you crave?', 'Name sensations', 1),
                ('How do you want me to initiate physical contact?', 'Guide my touch', 1),
                ('What is your favorite way to hold hands?', 'Describe hand holding', 1),
                ('Describe how you felt the first time we touched', 'Recall first touch', 2),
                ('What physical experience have you been dreaming about?', 'Share fantasy', 1),
                ('How do you like to move together?', 'Describe movement', 1),
                ('What makes you feel most physically desired?', 'Name desire triggers', 1),
                ('Describe your ideal moment of physical intimacy', 'Paint intimacy', 2),
                ('What do you love about my body?', 'Give physical praise', 1),
                ('How do you want to dance together?', 'Describe dance', 1),
                ('What physical sensation makes you feel most loved?', 'Name love sensations', 1),
                ('Describe a time you felt most physically confident', 'Share confidence', 1),
                ('What would you like to explore physically?', 'Share interests', 2),
                ('How do you want to wake up together?', 'Describe mornings', 1),
                ('What is your favorite physical memory with me?', 'Recall a moment', 1),
                ('Describe the perfect afternoon together', 'Paint perfect day', 1),
                ('How do you want to be held when vulnerable?', 'Guide comfort touch', 1),
                ('What physical play appeals to you?', 'Share play interests', 1),
                ('Describe your ideal shower or bath together', 'Paint water intimacy', 1),
                ('What makes you feel most physically alive?', 'Name vitality', 1),
                ('How do you want physical affection to increase?', 'Guide affection growth', 1),
                ('Describe the moment you felt most physically connected to me', 'Share peak connection', 2),
            ],
            'disagreeables': [
                ('What is the biggest argument we\'ve had?', 'Discuss conflict', 2),
                ('How do you typically react when angry?', 'Describe anger', 1),
                ('What habit of mine bothers you?', 'Be honest', 1),
                ('Describe a time I hurt you deeply', 'Share hurt', 2),
                ('What is something I do that frustrates you?', 'Name frustration', 1),
                ('How do you want me to handle your anger?', 'Guide anger support', 1),
                ('What topic are we most likely to argue about?', 'Name conflict topic', 1),
                ('How could I better support you during conflict?', 'Guide conflict support', 1),
                ('What unresolved issue still bothers you?', 'Face unresolved pain', 2),
                ('How do you think I could improve?', 'Give feedback', 1),
                ('What do you feel I don\'t understand about you?', 'Bridge gap', 1),
                ('Describe a time you felt abandoned by me', 'Share abandonment fear', 2),
                ('What is a deal-breaker for you in relationships?', 'Name deal-breakers', 1),
                ('How do you handle being wrong?', 'Explore accountability', 1),
                ('What fear comes up during arguments?', 'Name conflict fears', 1),
                ('Describe the worst moment in our relationship', 'Share difficult time', 2),
                ('How do you want to rebuild after a fight?', 'Guide reconciliation', 1),
                ('What do you feel I take for granted?', 'Name overlooked things', 1),
                ('How could we better communicate disagreements?', 'Improve communication', 1),
                ('What is something you\'ve never fully forgiven?', 'Face forgiveness', 2),
                ('How do you sabotage relationships?', 'Explore patterns', 1),
                ('What trigger makes you most defensive?', 'Name defensiveness', 1),
                ('Describe the coldest you\'ve felt toward me', 'Share distance', 2),
                ('How do you want to be approached when upset?', 'Guide approach', 1),
                ('What family pattern do you repeat?', 'Explore family patterns', 1),
                ('How do you handle my vulnerability?', 'Explore vulnerability handling', 1),
                ('What compromise is hard for you to make?', 'Name hard compromises', 1),
                ('Describe a time you felt misunderstood', 'Share misunderstanding', 1),
                ('What would make you consider leaving?', 'Be honest about limits', 2),
                ('How can we prevent future conflicts?', 'Build conflict prevention', 1),
            ],
            'romantic': [
                ('When did you first know you loved me?', 'Recall falling in love', 2),
                ('What is the most romantic thing someone has done for you?', 'Share romance', 2),
                ('Describe the perfect date for us', 'Plan ideal date', 1),
                ('How do you want me to romance you?', 'Guide romance', 1),
                ('What would make our relationship feel more special?', 'Enhance specialness', 1),
                ('Describe a moment you felt completely cherished', 'Share cherishment', 2),
                ('What is your greatest hope for us?', 'Share hope', 2),
                ('How do you want to celebrate our milestones?', 'Plan celebrations', 1),
                ('What romantic gesture means most to you?', 'Name meaningful gesture', 1),
                ('Describe our love story as you see it', 'Tell our story', 2),
                ('What would make you feel more courted?', 'Guide courting', 1),
                ('How do you want to express love in public?', 'Describe public affection', 1),
                ('What is the most loving thing I\'ve ever done?', 'Praise me', 2),
                ('Describe your ideal romantic getaway', 'Plan escape', 2),
                ('What do you love about our relationship?', 'Express appreciation', 1),
                ('How do you want our love to grow?', 'Plan growth', 1),
                ('What romantic dream should we pursue together?', 'Share dream', 2),
                ('Describe a moment you felt truly romanced by me', 'Share that moment', 2),
                ('What would make our intimate moments feel more romantic?', 'Enhance romance', 1),
                ('How do you want to be loved?', 'Express love needs', 1),
                ('What small gestures mean the most to you?', 'Name meaningful gestures', 1),
                ('Describe the person you want to become for us', 'Share your vision', 1),
                ('What is your favorite memory of us?', 'Recall favorite moment', 1),
                ('How do you want to stay connected to my heart?', 'Explore connection', 1),
                ('What would be the ultimate romantic gesture?', 'Describe dream gesture', 2),
                ('Describe how you want to grow old together', 'Paint our future', 2),
                ('What do you admire most about me?', 'Give deep compliment', 1),
                ('How can we keep romance alive?', 'Plan romance sustainability', 1),
                ('What is something you\'ve never told me that you love about me?', 'Share hidden love', 2),
                ('Describe the legacy of love you want to build', 'Share love legacy', 2),
            ],
            'erotic': [
                ('What is your biggest turn-on?', 'Share attraction', 1),
                ('Describe your fantasies about me', 'Share fantasies', 2),
                ('What would make you feel most sexually desired?', 'Name desire needs', 1),
                ('How do you like to initiate intimacy?', 'Describe initiation', 1),
                ('What is something you\'ve been curious to try?', 'Name curiosity', 1),
                ('Describe your favorite intimate memory', 'Recall peak intimacy', 2),
                ('What turns you on about my appearance?', 'Give erotic praise', 1),
                ('How do you like to be seduced?', 'Guide seduction', 1),
                ('What is your sexual love language?', 'Define it', 1),
                ('Describe the most satisfying sexual experience', 'Share satisfaction', 2),
                ('What would increase your desire for me?', 'Name desire enhancers', 1),
                ('How do you want to explore sexuality together?', 'Discuss exploration', 1),
                ('What do you love about our sexual connection?', 'Praise our sex', 1),
                ('Describe what makes you feel most sexually confident', 'Share confidence', 1),
                ('What sensation makes you lose control?', 'Name sensation', 1),
                ('How would you like our intimate life to evolve?', 'Plan evolution', 1),
                ('What fantasies have you kept private?', 'Share private fantasy', 2),
                ('Describe your ideal sexual rhythm with me', 'Paint rhythm', 1),
                ('What is off-limits for you sexually?', 'Name boundaries', 1),
                ('How do you want to express raw desire for me?', 'Guide expression', 1),
                ('What position or scenario excites you most?', 'Name excitement', 1),
                ('Describe the most passionate moment we\'ve shared', 'Recall passion', 2),
                ('What do you crave during intimate moments?', 'Name cravings', 1),
                ('How do you want me to touch you?', 'Guide touch', 1),
                ('What would be the ultimate sexual experience with me?', 'Describe ultimate', 2),
                ('How do you want foreplay to unfold?', 'Describe foreplay', 1),
                ('What turns you on about our differences?', 'Explore attraction', 1),
                ('Describe a moment of pure sexual connection', 'Share connection', 2),
                ('What would make you feel more sexually free?', 'Name freedom needs', 1),
                ('How can we create more sexual chemistry?', 'Build chemistry', 1),
            ],
            'creative': [
                ('What is your hidden talent?', 'Share talent', 1),
                ('Describe something you\'d like to create together', 'Plan creation', 1),
                ('What would be a fun challenge for us?', 'Suggest challenge', 1),
                ('Describe your ideal adventure', 'Paint adventure', 2),
                ('What hobby would you like to share with me?', 'Share hobby', 1),
                ('If you could do anything for a day, what would it be?', 'Describe dream day', 1),
                ('What creative project excites you?', 'Name excitement', 1),
                ('Describe a time you felt most inspired', 'Share inspiration', 1),
                ('What would you like to learn from me?', 'Name learning goal', 1),
                ('Describe the perfect creative collaboration', 'Paint collaboration', 1),
                ('What artistic form calls to you?', 'Name art form', 1),
                ('How do you like to have fun?', 'Describe fun', 1),
                ('What experience do you want to share?', 'Name experience', 1),
                ('Describe a place you\'d love to explore together', 'Plan exploration', 1),
                ('What makes you feel most alive and creative?', 'Name aliveness', 1),
                ('Describe your ideal weekend escape', 'Paint escape', 1),
                ('What talent of mine inspires you most?', 'Praise my talent', 1),
                ('How would you like to celebrate together?', 'Plan celebration', 1),
                ('What skill would you like to master together?', 'Name skill', 1),
                ('Describe a game we could play together', 'Invent game', 1),
                ('What spontaneous adventure appeals to you?', 'Name adventure', 1),
                ('How do you want to be playful together?', 'Describe playfulness', 1),
                ('What creative goal excites you for us?', 'Share creative goal', 1),
                ('Describe your ideal rainy day together', 'Paint day', 1),
                ('What would make ordinary moments feel special?', 'Enhance ordinary', 1),
                ('How do you want to express your personality with me?', 'Express fully', 1),
                ('Describe a tradition we should start', 'Create tradition', 1),
                ('What hidden dream should we pursue?', 'Share dream', 1),
                ('How can we inject more joy and laughter?', 'Plan joy', 1),
                ('Describe the most fun you\'ve ever had', 'Share peak fun', 1),
            ],
        }

        created_count = 0
        for category_name, questions_list in questions_data.items():
            category = categories[category_name]
            
            for idx, (question_text, consequence, points) in enumerate(questions_list, 1):
                question, created = Question.objects.get_or_create(
                    category=category,
                    question_text=question_text,
                    defaults={
                        'consequence': consequence,
                        'points': points,
                        'order': idx,
                    }
                )
                if created:
                    created_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f'Successfully created {created_count} questions across {len(questions_data)} categories'
            )
        )
