from django.core.management.base import BaseCommand
from django.db import transaction

from quiz.models import QuestionCategory, Question


class Command(BaseCommand):
    help = "Seed minimal questions for each category if none exist."

    @transaction.atomic
    def handle(self, *args, **options):
        created_categories = 0
        created_questions = 0

        for slug, label in QuestionCategory.CATEGORIES:
            name = label.split('(')[0].strip()
            category_obj, cat_created = QuestionCategory.objects.get_or_create(
                category=slug,
                defaults={
                    'name': name,
                    'description': f"Autogenerated category for {name}",
                },
            )
            if cat_created:
                created_categories += 1

            if category_obj.questions.exists():
                self.stdout.write(self.style.WARNING(f"Category '{slug}' already has questions; skipping."))
                continue

            samples = [
                {
                    'question_text': f"Sample question 1 for {name}.",
                    'points': 1,
                    'consequence': "Skip loses 1 point.",
                    'order': 1,
                },
                {
                    'question_text': f"Sample question 2 for {name}.",
                    'points': 2,
                    'consequence': "Skip loses 2 points.",
                    'order': 2,
                },
            ]

            for data in samples:
                Question.objects.create(category=category_obj, **data)
                created_questions += 1

            self.stdout.write(self.style.SUCCESS(f"Seeded {len(samples)} questions for category '{slug}'."))

        self.stdout.write(self.style.SUCCESS(
            f"Seeding complete: {created_categories} categories created, {created_questions} questions added."
        ))
