from django.urls import path
from .views import (
    SigninView, 
    SignupView, 
    UpdateProfilePictureView, 
    SearchUsersView,
    SendFriendRequestView,
    RespondFriendRequestView,
    RemoveFriendView,
    FriendsListView,
    PendingRequestsView,
    CreateGroupChatView,
    GroupChatListView,
    GroupChatDetailView,
    GroupMessagesView,
    AddGroupMembersView,
    CalendarListCreateView,
    CalendarDetailView,
    CalendarInviteView,
    CalendarEventListCreateView,
    CalendarEventDetailView,
    QuestionsListView,
    QuestionCategoriesView,
    RandomQuestionView,
    CreateGameSessionView,
    GameSessionDetailView,
    GameSessionListView,
    StartGameRoundView,
    SubmitAnswerView,
    GetAnswersView,
    NextRoundView,
    EndGameView,
    JoinGameByCodeView,
    JournalPromptsListView,
    RandomJournalPromptView,
    SharedJournalListCreateView,
    SharedJournalDetailView,
    SharedJournalMembersView,
    JournalEntryListCreateView,
    SharedPromptSessionListCreateView,
    SharedPromptSessionDetailView,
    SharedPromptSessionMembersView,
    PromptResponseListCreateView
)

urlpatterns = [
    path('signin/', SigninView.as_view(), name='signin'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('profile/picture/', UpdateProfilePictureView.as_view(), name='update-profile-picture'),
    path('search/users/', SearchUsersView.as_view(), name='search-users'),
    path('friends/request/send/', SendFriendRequestView.as_view(), name='send-friend-request'),
    path('friends/request/<int:request_id>/respond/', RespondFriendRequestView.as_view(), name='respond-friend-request'),
    path('friends/<int:friend_id>/remove/', RemoveFriendView.as_view(), name='remove-friend'),
    path('friends/', FriendsListView.as_view(), name='friends-list'),
    path('friends/requests/', PendingRequestsView.as_view(), name='pending-requests'),
    path('groups/create/', CreateGroupChatView.as_view(), name='create-group'),
    path('groups/', GroupChatListView.as_view(), name='group-list'),
    path('groups/<int:group_id>/', GroupChatDetailView.as_view(), name='group-detail'),
    path('groups/<int:group_id>/messages/', GroupMessagesView.as_view(), name='group-messages'),
    path('groups/<int:group_id>/add-members/', AddGroupMembersView.as_view(), name='add-group-members'),
    # Calendar routes
    path('calendars/', CalendarListCreateView.as_view(), name='calendar-list-create'),
    path('calendars/<int:calendar_id>/', CalendarDetailView.as_view(), name='calendar-detail'),
    path('calendars/<int:calendar_id>/invite/', CalendarInviteView.as_view(), name='calendar-invite'),
    path('calendars/<int:calendar_id>/events/', CalendarEventListCreateView.as_view(), name='calendar-events'),
    path('calendars/<int:calendar_id>/events/<int:event_id>/', CalendarEventDetailView.as_view(), name='calendar-event-detail'),
    # Question routes
    path('questions/categories/', QuestionCategoriesView.as_view(), name='question-categories'),
    path('questions/random/', RandomQuestionView.as_view(), name='random-question'),
    path('questions/random/<str:category>/', RandomQuestionView.as_view(), name='random-question-by-category'),
    path('questions/<str:category>/', QuestionsListView.as_view(), name='questions-by-category'),
    path('questions/', QuestionsListView.as_view(), name='questions-list'),
    # Multiplayer game routes
    path('games/create/', CreateGameSessionView.as_view(), name='create-game'),
    path('games/', GameSessionListView.as_view(), name='games-list'),
    path('games/<int:game_id>/', GameSessionDetailView.as_view(), name='game-detail'),
    path('games/<int:game_id>/start-round/', StartGameRoundView.as_view(), name='start-round'),
    path('games/<int:game_id>/submit-answer/', SubmitAnswerView.as_view(), name='submit-answer'),
    path('games/<int:game_id>/answers/', GetAnswersView.as_view(), name='get-answers'),
    path('games/<int:game_id>/next-round/', NextRoundView.as_view(), name='next-round'),
    path('games/<int:game_id>/end/', EndGameView.as_view(), name='end-game'),
    path('games/join/', JoinGameByCodeView.as_view(), name='join-game'),
    # Journal prompts routes (specific routes first)
    path('prompts/random/', RandomJournalPromptView.as_view(), name='random-journal-prompt'),
    path('prompts/', JournalPromptsListView.as_view(), name='journal-prompts-list'),
    # Shared journals routes
    path('journals/', SharedJournalListCreateView.as_view(), name='shared-journals-list-create'),
    path('journals/<int:journal_id>/', SharedJournalDetailView.as_view(), name='shared-journal-detail'),
    path('journals/<int:journal_id>/members/', SharedJournalMembersView.as_view(), name='shared-journal-members'),
    path('journals/<int:journal_id>/entries/', JournalEntryListCreateView.as_view(), name='journal-entries'),
    # Shared prompt sessions routes
    path('prompt-sessions/', SharedPromptSessionListCreateView.as_view(), name='shared-prompt-sessions-list-create'),
    path('prompt-sessions/<int:session_id>/', SharedPromptSessionDetailView.as_view(), name='shared-prompt-session-detail'),
    path('prompt-sessions/<int:session_id>/members/', SharedPromptSessionMembersView.as_view(), name='shared-prompt-session-members'),
    path('prompt-sessions/<int:session_id>/responses/', PromptResponseListCreateView.as_view(), name='prompt-responses'),
]