from django.urls import path
from .views import (
    SigninView, 
    SignupView, 
    UpdateProfilePictureView, 
    SearchUsersView,
    SendFriendRequestView,
    RespondFriendRequestView,
    FriendsListView,
    PendingRequestsView,
    CreateGroupChatView,
    GroupChatListView,
    GroupChatDetailView,
    GroupMessagesView,
    AddGroupMembersView,
    QuestionsListView,
    QuestionDetailView,
    SubmitAnswerView,
    UserResponsesView,
    CreateGameSessionView,
    GetRandomQuestionView,
    SubmitGameAnswerView,
    GameSessionDetailView,
    ActiveGameSessionsView,
    DeleteGameSessionView
)

urlpatterns = [
    path('signin/', SigninView.as_view(), name='signin'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('profile/picture/', UpdateProfilePictureView.as_view(), name='update-profile-picture'),
    path('search/users/', SearchUsersView.as_view(), name='search-users'),
    path('friends/request/send/', SendFriendRequestView.as_view(), name='send-friend-request'),
    path('friends/request/<int:request_id>/respond/', RespondFriendRequestView.as_view(), name='respond-friend-request'),
    path('friends/', FriendsListView.as_view(), name='friends-list'),
    path('friends/requests/', PendingRequestsView.as_view(), name='pending-requests'),
    path('groups/create/', CreateGroupChatView.as_view(), name='create-group'),
    path('groups/', GroupChatListView.as_view(), name='group-list'),
    path('groups/<int:group_id>/', GroupChatDetailView.as_view(), name='group-detail'),
    path('groups/<int:group_id>/messages/', GroupMessagesView.as_view(), name='group-messages'),
    path('groups/<int:group_id>/members/add/', AddGroupMembersView.as_view(), name='add-group-members'),
    path('questions/', QuestionsListView.as_view(), name='questions-list'),
    path('questions/<int:question_id>/', QuestionDetailView.as_view(), name='question-detail'),
    path('questions/answer/', SubmitAnswerView.as_view(), name='submit-answer'),
    path('questions/responses/', UserResponsesView.as_view(), name='user-responses'),
    path('game/create/', CreateGameSessionView.as_view(), name='create-game-session'),
    path('game/<int:session_id>/', GameSessionDetailView.as_view(), name='game-session-detail'),
    path('game/<int:session_id>/delete/', DeleteGameSessionView.as_view(), name='delete-game-session'),
    path('game/random-question/', GetRandomQuestionView.as_view(), name='get-random-question'),
    path('game/answer/', SubmitGameAnswerView.as_view(), name='submit-game-answer'),
    path('game/active/', ActiveGameSessionsView.as_view(), name='active-game-sessions'),
]