# Generated by ChatGPT on 2026-01-26

from django.db import migrations


def cleanup_legacy_tables(apps, schema_editor):
    connection = schema_editor.connection
    ops = connection.ops

    def q(name):
        return ops.quote_name(name)

    with connection.cursor() as cursor:
        existing_tables = set(connection.introspection.table_names(cursor))

        def table_columns(table_name):
            if table_name not in existing_tables:
                return set()
            description = connection.introspection.get_table_description(cursor, table_name)
            return {column.name for column in description}

        def rename_or_drop(old, new):
            if old not in existing_tables:
                return
            if new in existing_tables:
                cursor.execute(f"DROP TABLE {q(old)}")
                existing_tables.discard(old)
                return
            if connection.vendor == "mysql":
                cursor.execute(f"RENAME TABLE {q(old)} TO {q(new)}")
            else:
                cursor.execute(f"ALTER TABLE {q(old)} RENAME TO {q(new)}")
            existing_tables.discard(old)
            existing_tables.add(new)

        if "quiz_question" in existing_tables:
            question_columns = table_columns("quiz_question")
            legacy_question = "category_id" in question_columns or (
                "order" in question_columns and "question_number" not in question_columns
            )
            if legacy_question:
                rename_or_drop("quiz_question", "quiz_question_legacy")

        if "quiz_gamesession" in existing_tables:
            session_columns = table_columns("quiz_gamesession")
            legacy_session = "session_type" not in session_columns and "status" in session_columns
            if legacy_session:
                rename_or_drop("quiz_gamesession", "quiz_gamesession_legacy")
                rename_or_drop("quiz_gamesession_players", "quiz_gamesession_players_legacy")

        rename_or_drop("quiz_playeranswer", "quiz_playeranswer_legacy")
        rename_or_drop("quiz_questioncategory", "quiz_questioncategory_legacy")
        rename_or_drop("quiz_sharedcalendar", "quiz_sharedcalendar_legacy")
        rename_or_drop("quiz_calendarevent", "quiz_calendarevent_legacy")


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_groupchat_groupmessage"),
    ]

    operations = [
        migrations.RunPython(cleanup_legacy_tables, migrations.RunPython.noop),
    ]
