# Generated by Django 5.2.8 on 2025-12-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_question_questionresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('spiritual_knowing', 'Spiritual Knowing'), ('mental_knowing', 'Mental Knowing'), ('physical_knowing', 'Physical Knowing'), ('emotional_depth', 'Emotional Depth'), ('relational_truth', 'Relational Truth')], default='spiritual_knowing', max_length=50),
        ),
    ]
