# Generated by Django 5.2.8 on 2025-12-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('spiritual_knowing', 'Spiritual Knowing'), ('mental_knowing', 'Mental Knowing'), ('physical_knowing', 'Physical Knowing'), ('disagreeables_truth', 'Disagreeables & Truth Checks'), ('romantic_knowing', 'Romantic Knowing'), ('erotic_knowing', 'Erotic Knowing'), ('creative_fun', 'Creative & Fun')], default='spiritual_knowing', max_length=50),
        ),
    ]
