# Generated by Django 5.2.8 on 2025-12-30 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_gamesession_playeranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='game_sessions', to='quiz.questioncategory'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='current_turn_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_turn_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='game_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
