# Generated by Django 5.2.8 on 2025-12-17 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_gamesession_gameturn'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picker_answer', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('picker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picked_rounds', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_rounds', to='quiz.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='quiz.gamesession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='gameturn',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.gameround'),
        ),
        migrations.AlterUniqueTogether(
            name='gameturn',
            unique_together={('round', 'player')},
        ),
        migrations.RemoveField(
            model_name='gameturn',
            name='question',
        ),
        migrations.RemoveField(
            model_name='gameturn',
            name='session',
        ),
    ]
