# Generated by Django 5.2.8 on 2025-12-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_sharedpromptsession_promptresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncategory',
            name='category',
            field=models.CharField(choices=[('spiritual', 'Spiritual Knowing (1-20)'), ('mental', 'Mental Knowing (21-40)'), ('physical', 'Physical Knowing (41-60)'), ('disagreeables', 'Disagreeables & Truth Checks (61-80)'), ('romantic', 'Romantic Knowing (81-100)'), ('erotic', 'Desirable Knowing (101-160)'), ('creative', 'Creative & Fun (161-200)'), ('general', 'General Knowing (1-40)')], max_length=20, unique=True),
        ),
    ]
