# Generated by Django 5.2.8 on 2026-01-03 08:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('emoji', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('duration_days', models.IntegerField()),
                ('base_growth_rate', models.FloatField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SharedGarden',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Acceptance'), ('active', 'Active'), ('bloomed', 'Bloomed'), ('abandoned', 'Abandoned'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('both_planted_at', models.DateTimeField(blank=True, null=True)),
                ('invitation_message', models.TextField(blank=True, default='')),
                ('invitation_expires_at', models.DateTimeField(blank=True, null=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gardens.plant')),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gardens_created', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gardens_joined', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrowthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.IntegerField(default=1)),
                ('stage_started_at', models.DateTimeField(auto_now_add=True)),
                ('growth_percentage', models.FloatField(default=0.0)),
                ('growth_updated_at', models.DateTimeField(auto_now_add=True)),
                ('current_streak_days', models.IntegerField(default=0)),
                ('streak_started_at', models.DateTimeField(blank=True, null=True)),
                ('all_time_max_streak', models.IntegerField(default=0)),
                ('health_status', models.CharField(choices=[('thriving', 'Thriving'), ('healthy', 'Healthy'), ('declining', 'Declining'), ('wilting', 'Wilting'), ('dead', 'Dead')], default='healthy', max_length=20)),
                ('last_care_action_at', models.DateTimeField(blank=True, null=True)),
                ('days_since_last_care', models.IntegerField(default=0)),
                ('is_bloomed', models.BooleanField(default=False)),
                ('bloom_type', models.CharField(choices=[('pending', 'Not Yet'), ('perfect', 'Perfect'), ('partial', 'Partial'), ('auto_complete', 'Auto-Completed')], default='pending', max_length=20)),
                ('bloom_timestamp', models.DateTimeField(blank=True, null=True)),
                ('bloomed_at_streak', models.IntegerField(default=0)),
                ('final_care_score', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='growth_state', to='gardens.sharedgarden')),
            ],
        ),
        migrations.CreateModel(
            name='CareAction',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('water', 'Water'), ('meditation', 'Meditation'), ('message', 'Message')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('points_earned', models.IntegerField(default=0)),
                ('growth_delta', models.FloatField(default=0.0)),
                ('is_synchronized', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_actions', to=settings.AUTH_USER_MODEL)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_actions', to='gardens.sharedgarden')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='sharedgarden',
            index=models.Index(fields=['user_a', 'status'], name='gardens_sha_user_a__6dc0bb_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedgarden',
            index=models.Index(fields=['user_b', 'status'], name='gardens_sha_user_b__c0f83e_idx'),
        ),
        migrations.AddIndex(
            model_name='careaction',
            index=models.Index(fields=['garden', '-timestamp'], name='gardens_car_garden__e74a6b_idx'),
        ),
        migrations.AddIndex(
            model_name='careaction',
            index=models.Index(fields=['user', '-timestamp'], name='gardens_car_user_id_c938fa_idx'),
        ),
    ]
